default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: voice_log_development


test:
  <<: *default
  database: voice_log_test


production:
  <<: *default
  database: voice_log_production
  username: voice_log
  password: <%= ENV['VOICE_LOG_DATABASE_PASSWORD'] %>
