# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: adb2c9dcbfebe4a0f762ec99f241239d402fc8126515955d3bf0f2efdcaf054942411cba0c216df076ecdcd3f64cf0d5274510693858497176edaac4b4601f8c

test:
  secret_key_base: 654f9688af2181af98272a70f716076546c78d60c143267f63c280cc43a9eac52f29ae7cb4395ece9634ed66663ffefd9cd42c3835852124f54b6fdf6133c6f1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
